mod 'feedlabs/php5',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/php5'

mod 'feedlabs/openssl',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/openssl'

mod 'feedlabs/apache2',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/apache2'

mod 'feedlabs/mysql',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/mysql'

mod 'feedlabs/rsync',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/rsync'

mod 'feedlabs/helper',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/helper'
