language: ruby
rvm: 1.8.7
env:
  - PUPPET_VERSION=3.3.0
script:
  - bundle exec rake validate
  - bundle exec rake lint

before_install:
  - gem update --system 2.1.11 #  todo: workaround for https://github.com/rubygems/rubygems/pull/763
