mod 'feedlabs/build',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/build'

mod 'feedlabs/apache2',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/apache2'

mod 'feedlabs/ruby',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/ruby'
