mod 'feedlabs/apt',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/apt'

mod 'feedlabs/apache2',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/apache2'

mod 'feedlabs/build',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/build'

mod 'feedlabs/helper',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/helper'

mod 'feedlabs/gearmand',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/gearmand'

mod 'feedlabs/monit',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/monit'

mod 'feedlabs/bipbip',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/bipbip'
