mod 'feedlabs/sysctl',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/sysctl'

mod 'feedlabs/ulimit',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/ulimit'

mod 'feedlabs/monit',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/monit'

mod 'feedlabs/bipbip',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/bipbip'

mod 'feedlabs/database',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/database'
