mod 'feedlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'feedlabs/ssh',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/ssh'

mod 'feedlabs/helper',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/helper'

mod 'feedlabs/monit',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/monit'

mod 'feedlabs/git',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/git'

mod 'feedlabs/ruby',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/ruby'

mod 'feedlabs/librarian_puppet',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/librarian_puppet'

mod 'feedlabs/passenger',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/passenger'

mod 'feedlabs/apache2',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/apache2'
