mod 'build',
  :git => 'git@github.com:mariansollmann/puppet-packages.git',
  :path => 'modules/build'

mod 'helper',
  :git => 'git@github.com:mariansollmann/puppet-packages.git',
  :path => 'modules/helper'
