mod 'build',
  :git => 'git@github.com:mariansollmann/puppet-packages.git',
  :path => 'modules/build'

mod 'helper',
  :git => 'git@github.com:mariansollmann/puppet-packages.git',
  :path => 'modules/helper'

mod 'monit',
  :git => 'git@github.com:mariansollmann/puppet-packages.git',
  :path => 'modules/monit'

mod 'bipbip',
  :git => 'git@github.com:mariansollmann/puppet-packages.git',
  :path => 'modules/bipbip'
