mod 'feedlabs/build',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/build'

mod 'feedlabs/helper',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/helper'

mod 'feedlabs/monit',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/monit'

mod 'feedlabs/bipbip',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/bipbip'
