mod 'feedlabs/helper',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/helper'

mod 'feedlabs/monit',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/monit'

mod 'feedlabs/golang',
  :git => 'git@github.com:feedlabs/puppet-packages.git',
  :path => 'modules/golang'
